### ISSUE TITLE
Custom CSS doesn't support 'fr' units

### ISSUE THREAD

**Issue by rinart73** [Codeinwp/otter-blocks#1494]
### Description:
I'm trying to create a CSS grid that uses "fr" units:
```css
selector > .wp-block-group__inner-container {
  display: grid;
  grid-template-columns: repeat(8, minmax(min-content, max-content));
  grid-auto-rows: 1fr;
}
```
I'm getting an error:
`Attention needed! We found following errors with your code: Unexpected token '1fr' at line 4, col 19.`

### How to reproduce:

1. Add custom CSS that uses the "fr" unit
2. Get an error

### Expected behaviour:
Supported fr units.

### Current behaviour:
An attempt to use fr units causes parsing error and prevents CSS from being saved.

### Reference:
![image](https://user-images.githubusercontent.com/1765611/218570100-63e06ac6-ed17-4652-9af4-828d8ab4cbf0.png)

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.2.2
